global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "devops-project"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "todo-app"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["app:3000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "todo-app"
